version: '3'
services:
  mysql:
    container_name: db
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'P4ssW0rD'
      MYSQL_USER: 'python_user'
      MYSQL_PASS: 'P4ssW0rD'
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
